### ISSUE TITLE
Implement "vault unlock" method in testing tool

### ISSUE THREAD

**Issue by petr-inmite** [lime-company/lime-security-powerauth#47]
Currently, the Java command line tool does not have a "unlock" method to check the vault unlocking.

As a result, this endpoint is not well tested.

**Comment by Vanyaslav** [comment]
It's not working at all. Please offer an correct solution. 

```log
Request heaaders: {
    "Accept-Language" = "en;q=1, fr;q=0.9, de;q=0.8, zh-Hans;q=0.7, zh-Hant;q=0.6, ja;q=0.5";
    "Content-Type" = "application/json";
    "Demo-User" = true;
    "User-Agent" = "GeMoney/1.0.0 (iOS; 9.1.1; iPhone; iPhone 5s)";
    "X-PowerAuth-Authorization" = "PowerAuth pa_activation_id=\"31b57718-e860-4a7c-8d5a-20fac8ae2fe7\"pa_application_id=\"a1c97807-795a-466e-87bf-230d8ac1451e\"pa_signature=\"92287634-53447585\"pa_signature_type=\"possession_knowledge\"pa_nonce=\"3CCv/hPUpULZ7MdSDgobsg==\"pa_version=\"2.0\"";
}
2016-02-17 19:53:10.641 HawkNestModuleTest[39302:7949079] Request body: {
  "requestObject" : {

  }
}
2016-02-17 19:53:10.641 HawkNestModuleTest[39302:7949079] Request URL: http://localhost:8080/powerauth-restful-server/pa/vault/unlock
2016-02-17 19:53:10.641 HawkNestModuleTest[39302:7949079] Request method: POST
2016-02-17 19:53:10.660 HawkNestModuleTest[39302:7949079] Error: Request failed: bad request (400)
2016-02-17 19:53:10.660 HawkNestModuleTest[39302:7949079] Error mas: {
    NSErrorFailingURLKey = "http://localhost:8080/powerauth-restful-server/pa/vault/unlock";
    NSLocalizedDescription = "Request failed: bad request (400)";
```
```log
org.springframework.ws.soap.client.SoapFaultClientException: Unknown exception has occurred
        at org.springframework.ws.soap.client.core.SoapFaultMessageResolver.resolveFault(SoapFaultMessageResolver.java:38)
        at org.springframework.ws.client.core.WebServiceTemplate.handleFault(WebServiceTemplate.java:830)
        at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:624)
        at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555)
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:390)
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:383)
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:373)
        at io.getlime.security.soap.client.PowerAuthServiceClient.unlockVault(PowerAuthServiceClient.java:259)
        at io.getlime.security.soap.client.PowerAuthServiceClient.unlockVault(PowerAuthServiceClient.java:274)
        at io.getlime.rest.api.security.controller.SecureVaultController.unlockVault(SecureVaultController.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:775)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
```

**Comment by petr-inmite** [comment]
The issue is submitted, "vault unlock" is not implemented in the testing tool. It's auxiliary feature, though - not a big problem for now, so "low prio".

**Comment by petr-inmite** [comment]
Read https://github.com/lime-company/lime-security-powerauth/blob/master/powerauth-docs/source/tutorial/console-client-app.md#unlock-the-secure-vault for an example usage.
